language: python

python:
  - 2.7

os:
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y g++ icu-devtools ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                                                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install icu4c                                                           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig:$PKG_CONFIG_PATH" ; fi
  - make

install:
  - for P in dist/*.whl; do env pip install ${P}; done;

script: make test
