sudo: required

language: generic

matrix:
  include:
    - os: linux
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y g++ icu-devtools
        - sudo apt-get install -y python3-setuptools python3-pip
        - sudo pip3 install --upgrade pip setuptools
      install:
        - python3 setup.py sdist
        - sudo pip3 install tfucops -f dist/
      script: for TEST in tests/*.py; do python3 $TEST; done
    - os: osx
      before_install:
        - brew update
        - brew install python icu4c || true
        - brew upgrade python icu4c || true
        - export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig:$PKG_CONFIG_PATH"
        - sudo pip2 install --upgrade pip setuptools
      install:
        - python2 setup.py sdist
        - sudo pip2 install tfucops -f dist/
      script: for TEST in tests/*.py; do python2 $TEST; done

deploy:
  provider: pypi
  distributions: sdist
  user: shkarupa.alex
  password:
    secure: AH6IdSDHTa+tE/w/4zWP+S4lDpRgQt2SjGGzLk4/doV6xvLTIsFpd57zjW+RX/aWcixphKT3qAKCpJBEKg6m3lHEFJZP8X4rN+OZ4D0i86iuJXgwObB0gzhpbWroNYwOP4fY3rnEMB67/Gae4GUFijA1BcxSFZ4FM2SnQCM7mzq1/fLeNmdme0vZ+/00vAUWwJ2uiUPLIDM2GqA56YEKrtAY/5Twaec3dK43ODbnLIoFGWvGtaPKmtyo+DudTXt2+e28RzDO5RQud9WaH+9sFVxN1Iayh0jjKjognICCJPgT8YmPkn2BJWn5YOETrCPmxD9Nvag/Qw94fFOXIOwoFzC8+ckyWc7y2PB1VcZFcyT0GO2UuzVBr8p+SSed3hTxf1NF4U3qXZXtYzobWXnaGeZhaQIr5JFblZb4gzkjfKfHVA1bmK2zm7JGstYRWMApO6WgpkIg2BfCehpothfg94LnD9hSHcE+OH/kHgWT0PNd22ovX2TB3WN88kiIKznagvHsniX/Sj43xu4CLI5tYz6dfsSpgU8VEAJ6/WZJ98Wqzr3uIGb/imJEJyYSHA7n6/lEjwPIaFUZv0cCexaRNOIdaM9V7eFovLIuff9PibsBDuhzSs+gH6gZSCroidI4BfKL1R//Tm5Uaak7vvVTZPkadeQ4esw9e0jMYF73QT4=
  on:
    branch: master
