sudo: required

language: generic

matrix:
  include:
    - os: linux
      env:
        - PYTHON_BIN=python3
        - LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y pkg-config python3 python3-setuptools python3-pip g++ wget
        - wget -qO- http://download.icu-project.org/files/icu4c/61.1/icu4c-61_1-src.tgz | tar xvz
        - (cd icu/source && ./configure && make && sudo make install)
        - sudo $PYTHON_BIN -m pip install -U pip setuptools
        - sudo $PYTHON_BIN -m pip install -U tensorflow
    - os: osx
      env:
        - PYTHON_BIN=python
        - PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig:$PKG_CONFIG_PATH"
        - PATH="/usr/local/opt/python/libexec/bin:$PATH"
      before_install:
        - brew update
        - brew install pkg-config python gcc icu4c || true
        - brew upgrade pkg-config python gcc icu4c || true
        - $PYTHON_BIN -m pip install -U pip setuptools
        - $PYTHON_BIN -m pip install -U tensorflow

script: $PYTHON_BIN setup.py test
