sudo: required

language: generic

matrix:
  include:
    - os: linux
      env:
        - PYTHON_BIN=python3
        - PIP_BIN=pip3
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y pkg-config python3 python3-setuptools python3-pip g++ wget
        - wget -qO- http://download.icu-project.org/files/icu4c/60.2/icu4c-60_2-src.tgz | tar xvz
        - (cd icu/source && ./configure && make && sudo make install)
        - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
      script: sudo env LD_LIBRARY_PATH=$LD_LIBRARY_PATH PYTHON_BIN=$PYTHON_BIN PIP_BIN=$PIP_BIN make
    - os: osx
      env:
        - PYTHON_BIN=python2
        - PIP_BIN=pip2
      before_install:
        - brew update
        - brew upgrade pkg-config python gcc icu4c
        - export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig:$PKG_CONFIG_PATH"
      script: make
