package(default_visibility = ["//visibility:public"])

py_library(
    name = "tfunicode",
    srcs = ["__init__.py"],
    srcs_version = "PY2AND3",
    deps = [
        "//tfunicode/python",
    ],
)
