package(default_visibility = ["//tfunicode:__subpackages__"])


py_test(
    name = "combine_sparse_successor_test",
    srcs = ["combine_sparse_successor_test.py"],
    srcs_version = "PY2AND3",
    deps = [
        "@org_tensorflow//tensorflow:tensorflow_py",
        "//tfunicode/python",
    ],
)


py_test(
    name = "expand_char_ngrams_test",
    srcs = ["expand_char_ngrams_test.py"],
    srcs_version = "PY2AND3",
    deps = [
        "@org_tensorflow//tensorflow:tensorflow_py",
        "//tfunicode/python",
    ],
)


py_test(
    name = "expand_split_chars_test",
    srcs = ["expand_split_chars_test.py"],
    srcs_version = "PY2AND3",
    deps = [
        "@org_tensorflow//tensorflow:tensorflow_py",
        "//tfunicode/python",
    ],
)


py_test(
    name = "expand_split_words_test",
    srcs = ["expand_split_words_test.py"],
    srcs_version = "PY2AND3",
    deps = [
        "@org_tensorflow//tensorflow:tensorflow_py",
        "//tfunicode/python",
    ],
    data = [':WordBreakTest.txt']
)


py_test(
    name = "transform_lower_case_test",
    srcs = ["transform_lower_case_test.py"],
    srcs_version = "PY2AND3",
    deps = [
        "@org_tensorflow//tensorflow:tensorflow_py",
        "//tfunicode/python",
    ],
)


py_test(
    name = "transform_normalize_unicode_test",
    srcs = ["transform_normalize_unicode_test.py"],
    srcs_version = "PY2AND3",
    deps = [
        "@org_tensorflow//tensorflow:tensorflow_py",
        "//tfunicode/python",
    ],
)


py_test(
    name = "transform_upper_case_test",
    srcs = ["transform_upper_case_test.py"],
    srcs_version = "PY2AND3",
    deps = [
        "@org_tensorflow//tensorflow:tensorflow_py",
        "//tfunicode/python",
    ],
)


py_test(
    name = "transform_wrap_with_test",
    srcs = ["transform_wrap_with_test.py"],
    srcs_version = "PY2AND3",
    deps = [
        "@org_tensorflow//tensorflow:tensorflow_py",
        "//tfunicode/python",
    ],
)


py_test(
    name = "transform_zero_digits_test",
    srcs = ["transform_zero_digits_test.py"],
    srcs_version = "PY2AND3",
    deps = [
        "@org_tensorflow//tensorflow:tensorflow_py",
        "//tfunicode/python",
    ],
)
